
repos:
    -
        repo: 'https://github.com/ambv/black'
        # 24
        rev: e026c93888f91a47a9c9f4e029f3eb07d96375e6
        hooks:
            - id: black
              args: ['--safe']
              language_version: python3.11
    -
        repo: 'https://github.com/pycqa/flake8'
        # v7.0.0
        rev: 88a4f9b2f48fc44b025a48fa6a8ac7cc89ef70e0
        hooks:
            - id: flake8
              language_version: python3.11
              args: [
                  # E501 let black handle all line length decisions
                  # W503 black conflicts with "line break before operator" rule
                  # E203 black conflicts with "whitespace before ':'" rule
                  '--ignore=E501,W503,E203']
    -
        repo: 'https://github.com/chewse/pre-commit-mirrors-pydocstyle'
        # 6.3.0
        rev: 22d3ccf6cf91ffce3b16caa946c155778f0cb20f
        hooks:
            - id: pydocstyle
              language_version: python3.11
              args: [
                 # Check for docstring presence only
                 '--select=D1',
                 # Don't require docstrings for tests
                 '--match=(?!test).*\.py']
